namespace GoldbApi.DTOs;

public class ReceivableDto
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public string? UserName { get; set; }

    public string? UserDisplayName { get; set; }

    // The retailer's own RTL company name (falls back to their first company if they have no
    // RTL membership) - mirrors UserReceivableSummaryDto.CompanyName, so 정산 완료 내역's
    // "거래처" column shows the same identity 미수금 관리 already does, not just the raw
    // user display name.
    public string? CompanyName { get; set; }

    public int? OrderId { get; set; }

    public string? OrderNo { get; set; }

    public string? ProductName { get; set; }

    public string? ProductPhotoUrl { get; set; }

    public string Type { get; set; } = string.Empty;

    public decimal Amount { get; set; }

    public decimal RemainingAmount { get; set; }

    public decimal Weight { get; set; }

    public decimal RemainingWeight { get; set; }

    public string? Memo { get; set; }

    public string? SettlementMethod { get; set; }

    public decimal Discount { get; set; }

    public bool IsCancelled { get; set; }

    public DateTime CreatedAt { get; set; }

    // Only set for a DEPOSIT auto-generated by a 정산처리 (Payable) payment - lets the
    // frontend block manual edit/cancel here and point the user to the source payment instead.
    public int? SourcePaymentId { get; set; }

    // Only populated for DEPOSIT rows - which charge(s) this payment actually paid
    // off, since a payment can spill over past its own order into other outstanding
    // charges (oldest first) once its tagged order is fully covered.
    public List<AppliedChargeDto> AppliedCharges { get; set; } = new();

    // For a DEPOSIT row: the current (as of now) unsettled RemainingAmount/RemainingWeight
    // summed across every charge this deposit's applications touched - mirrors PayableDto's
    // OutstandingChargeAmount, lets the DCC transaction list distinguish a deposit that fully
    // closed its charge(s) from one that only partially covered them.
    public decimal OutstandingChargeAmount { get; set; }

    public decimal OutstandingChargeWeight { get; set; }

    // Mirrors PayableDto's OrderCount - how many distinct orders a DEPOSIT's applications
    // touched, for the "거래 주문 수량" column.
    public int OrderCount { get; set; }

    // Mirrors PayableDto's IsMostRecentPayment - true only for a DEPOSIT row that has no
    // later (non-cancelled) DEPOSIT for the same retailer, since editing an older one after a
    // newer one already exists would invalidate later chronological ledger calculations.
    public bool IsMostRecentPayment { get; set; }
}

public class AppliedChargeDto
{

    public int ChargeId { get; set; }

    public int? OrderId { get; set; }

    public string? OrderNo { get; set; }

    public decimal AppliedAmount { get; set; }

    public decimal AppliedWeight { get; set; }

    public decimal ChargeAmount { get; set; }

    public decimal ChargeWeight { get; set; }

    // Live remaining balance on the charge itself, as of now - used the same way Payable's
    // chargeRemainingAmount/chargeRemainingWeight are: to tell "this application's own
    // weight/amount happened to be 0" apart from "nothing was actually owed".
    public decimal ChargeRemainingAmount { get; set; }

    public decimal ChargeRemainingWeight { get; set; }

    public List<ReceivableOrderItemSummaryDto> Items { get; set; } = new();
}

public class UserReceivableSummaryDto
{

    public int UserId { get; set; }

    public string? UserName { get; set; }

    public string? UserDisplayName { get; set; }

    public string? CompanyName { get; set; }

    public decimal TotalCharge { get; set; }

    public decimal TotalDeposit { get; set; }

    public decimal TotalReceivable { get; set; }

    public decimal TotalChargeWeight { get; set; }

    public decimal TotalDepositWeight { get; set; }

    public decimal TotalReceivableWeight { get; set; }

    public DateTime? LastPaymentDate { get; set; }

    // Only populated by GetReceivableChargeSummaryAsync(orderIds) - the selected charges'
    // own totals/breakdown/per-order rows, for the batch-settle dialog. Left empty by
    // GetUserSummariesAsync's plain per-user aggregate (unrelated to any specific selection).
    public decimal SaleAmount { get; set; }

    public decimal SaleWeight { get; set; }

    public List<PurityBreakdownDto> PurityBreakdown { get; set; } = new();

    public List<ReceivableChargeSummaryItemDto> Items { get; set; } = new();
}

public class ReceivableChargeSummaryItemDto
{

    public int ReceivableId { get; set; }

    public int? OrderId { get; set; }

    public string? OrderNo { get; set; }

    public string? ProductName { get; set; }

    public string? ProductNo { get; set; }

    public string? ProductPhotoUrl { get; set; }

    public string? Purity { get; set; }

    public string? Color { get; set; }

    public string? Size { get; set; }

    public string? Memo { get; set; }

    public int Quantity { get; set; }

    public decimal ChargeWeight { get; set; }

    public decimal? ActualWeight { get; set; }

    public decimal RemainingAmount { get; set; }

    public DateTime OrderDate { get; set; }

    // An order can bundle several distinct products, not just one - the singular
    // ProductName/Purity/Quantity/ActualWeight fields above only ever reflected the first
    // top-level item, silently dropping the rest for a multi-product order. This carries
    // every top-level item so the settlement dialog can list them all.
    public List<ReceivableOrderItemSummaryDto> Items { get; set; } = new();
}

public class PuritySummaryDto
{

    public decimal Purity14k { get; set; }

    public decimal Purity18k { get; set; }

    public decimal PureGold { get; set; }

    public decimal PurityPt { get; set; }
}

public class ReceivableQueryDto
{

    public int Page { get; set; } = 1;

    public int PageSize { get; set; } = 20;

    public int? UserId { get; set; }

    // The 거래처/소매점 filter (SettlementHistoryFilter's <company-select category="RTL">)
    // picks a Company, not a User - resolved server-side to that company's user(s) since
    // Receivable rows are keyed by UserId, not CompanyId.
    public int? CompanyId { get; set; }

    public string? Type { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string? OrderNo { get; set; }

    public string? ProductNo { get; set; }

    public string? ProductName { get; set; }

    public int? ManufacturerId { get; set; }

    public string? CategoryLarge { get; set; }

    public string? CategoryMedium { get; set; }

    public string? CategorySmall { get; set; }
}

public class CreateDepositDto
{

    public int UserId { get; set; }

    public int? OrderId { get; set; }

    public List<int>? OrderIds { get; set; }

    public decimal Amount { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Discount { get; set; }

    public string? Memo { get; set; }

    public string? SettlementMethod { get; set; }
}

public class UpdateDepositDto
{

    public decimal Amount { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Discount { get; set; }

    public string? Memo { get; set; }

    public string? SettlementMethod { get; set; }
}

public class LogisticsReceivableSummaryDto
{

    public decimal TotalUnpaid { get; set; }

    public decimal CurrentMonthCharge { get; set; }

    public decimal CurrentMonthDeposit { get; set; }

    public decimal CurrentMonthUnpaid { get; set; }

    public List<RetailerReceivableSummaryDto> RetailerSummaries { get; set; } = new();
}

public class RetailerReceivableSummaryDto
{
    public int CompanyId { get; set; }
    public string CompanyName { get; set; } = string.Empty;
    public decimal TotalUnpaid { get; set; }
    public decimal CurrentMonthCharge { get; set; }
    public decimal CurrentMonthDeposit { get; set; }
}

// DCC's "정산 대상 내역" (물류도착 이후 - 소매점에게서 수금할 목록) - mirrors PayableQueryDto/
// PayableOrderRowDto's shape, but keyed by the ordering USER (retailer) rather than a company.
public class ReceivableOrderHistoryQueryDto
{

    public int Page { get; set; } = 1;

    public int PageSize { get; set; } = 20;

    public int? UserId { get; set; }

    public string? ProductName { get; set; }

    public string? Remarks { get; set; }
}

public class ReceivableOrderRowDto
{

    public int ReceivableId { get; set; }

    public int? OrderId { get; set; }

    public string? OrderNo { get; set; }

    public string? ProductName { get; set; }

    public string? ProductPhotoUrl { get; set; }

    public int ProductItemCount { get; set; }

    public List<ReceivableOrderItemSummaryDto> Items { get; set; } = new();

    public int UserId { get; set; }

    public string? UserName { get; set; }

    public string? UserDisplayName { get; set; }

    public string? RetailerCompanyName { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal ChargeAmount { get; set; }

    public decimal ChargeWeight { get; set; }

    public decimal PaidAmount { get; set; }

    public decimal PaidWeight { get; set; }

    public decimal RemainingAmount { get; set; }

    public decimal RemainingWeight { get; set; }
}

public class ReceivableOrderItemSummaryDto
{

    public string? ProductName { get; set; }

    public string? ProductNo { get; set; }

    public string? PhotoUrl { get; set; }

    public string? Purity { get; set; }

    public string? Color { get; set; }

    public string? Size { get; set; }

    public string? Memo { get; set; }

    public int Quantity { get; set; }

    public decimal? ActualWeight { get; set; }

    // Retailer-facing cost (falls back to the factory's own input cost when the retailer
    // hasn't confirmed one) - needed for 거래명세서's "공임비" column, same convention
    // GetReceivableChargeSummaryAsync's purity/sale-amount totals already use.
    public decimal MaterialCost { get; set; }

    public decimal LaborCost { get; set; }
}

public class ReceivableOrderHistorySummaryDto
{

    public decimal TotalChargeAmount { get; set; }

    public decimal TotalChargeWeight { get; set; }

    public decimal TotalPaidAmount { get; set; }

    public decimal TotalPaidWeight { get; set; }
}

public class ReceivableOverdueQueryDto
{

    public int? UserId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }
}

// 미수금 관리 (DCC's own overdue-collections tracker) - one row per retailer that has
// received at least one partial payment on a charge but still owes something. Mirrors
// PayableOverdueRowDto's MFG-side convention exactly, grouped by retailer instead of by
// DCC partner.
public class ReceivableOverdueRowDto
{

    public int UserId { get; set; }

    public string? CompanyName { get; set; }

    public string? UserDisplayName { get; set; }

    // Oldest still-outstanding charge's own date - what 연체 일수 counts forward from.
    public DateTime SaleDate { get; set; }

    public decimal SaleAmount { get; set; }

    public decimal SaleWeight { get; set; }

    public decimal CollectedAmount { get; set; }

    public decimal CollectedWeight { get; set; }

    public decimal OutstandingAmount { get; set; }

    public decimal OutstandingWeight { get; set; }

    public int OverdueDays { get; set; }

    // Feeds ReceivableBatchSettleDialog's order-ids prop for the "입금처리" action.
    public List<int> OrderIds { get; set; } = new();
}

// One row per DEPOSIT that paid off a given CHARGE - lets 주문별 보기's expand show which
// transaction(s) closed out this order instead of only the flat 거래별 보기 list, mirrors
// Payable's ChargeApplicationRowDto exactly.
public class ReceivableChargeApplicationRowDto
{

    public int DepositId { get; set; }

    public decimal AppliedAmount { get; set; }

    public decimal AppliedWeight { get; set; }

    public DateTime DepositCreatedAt { get; set; }

    public bool IsCancelled { get; set; }

    public string? Memo { get; set; }

    // The deposit's OWN recorded amount/weight/discount (as opposed to AppliedAmount/
    // AppliedWeight above, which is only the portion allocated to THIS charge) - needed so
    // this row is self-sufficient for editing/cancelling the deposit directly from the
    // nested history view, without a second round-trip to fetch the full deposit record.
    public decimal Amount { get; set; }

    public decimal Weight { get; set; }

    public decimal Discount { get; set; }

    // Set when this deposit was auto-generated by a 정산처리 (Payable) payment - blocks
    // manual edit/cancel here, same rule already enforced by the API for a direct deposit.
    public int? SourcePaymentId { get; set; }
}
